### ISSUE TITLE
Endpoints returns 404 error

### ISSUE THREAD

**Issue by lividavi19** [SmartableAI/developer-program#18] opened 2020-05-11 13:25 UTC
The API endpoints, the stats and news returns 404 not found error.
Been experiencing this behavior since around noon today.

STATS ENDPOINT: https://api.smartable.ai/coronavirus/stats/{location}
NEWS ENDPOINT: https://api.smartable.ai/coronavirus/news/{location}

**Comment by seemane** [comment] 2020-05-11 17:10
I have used the global news endpoints. It returns 404 not found error.

**Comment by SmartableAI** [comment] 2020-05-11 17:53
Sorry there was an outage.  The problem is fixed now.

**Comment by lividavi19** [comment] 2020-05-11 17:58
OK, that's a relief. Closing the issue now....

**Closed as completed** 2020-05-11 17:58 UTC
